name: Call_Of_Duty
main: GLF\COD\CODmain
version: "1.0.0"
api:
- '*'
author: GabboMCPE

commands:
    cod:
        usage: /cod crea <nomearena>
        description: Crea una arena
    codstart:
        usage: /codstart
        description: Forza l'inizio di una partita
